sph: fixed build issue if Silo enabled
This patch fixes the following build error, if Silo is found on the
system:

Scanning dependencies of target sph
[ 93%] Building CXX object
examples/smoothed_particle_hydrodynamics/CMakeFiles/sph.dir/main.cpp.o
/home/kurt/git/libflatarray/examples/smoothed_particle_hydrodynamics/main.cpp:3:10:
fatal error: 'silo.h' file not found
         ^
1 error generated.
*** Error code 1

Problem: the include directory for silo.h was missing. This patch adapts
the CMakeLists.txt accordingly.